version: '3'

vars:
  APP_NAME: "visutask"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 5173}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: build:backend

  build:backend:
    summary: Builds the Go backend
    cmds:
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} .

  build:frontend:
    summary: Builds the React frontend
    dir: frontend
    cmds:
      - pnpm install
      - pnpm build

  run:
    summary: Runs the application
    cmds:
      - '{{.BIN_DIR}}/{{.APP_NAME}}'

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
